### ISSUE TITLE
[Suggestion]: Homeostatic support

### ISSUE THREAD

**Issue by AK-Chester** [Fuzss/leavemybarsalone#1]
Support for [Homeostatic](https://www.curseforge.com/minecraft/mc-mods/homeostatic) would be nice. Its thirst bar is overlapping sometimes.

Mods used:
AppleSkin
Homeostatic
Leave My Bars Alone
Raised

**Comment by AK-Chester** [comment]
Thanks for "redirecting" this. I wasn't sure where to post it.

**Comment by Fuzss** [comment]
Should be fixed in Homeostatic, thanks for reporting!

**Comment by wendall911** [comment]
The latest for 1.18.2 and 1.19 are published on CurseForge now with the fix. @AK-Chester Thanks for reporting.

**Comment by AK-Chester** [comment]
@wendall911 & @Fuzss
Awesome, thank you!
