### ISSUE TITLE
[Crash]: When eating carrots on a horse with Appleskin mod.

### ISSUE THREAD

**Issue by Ezeyra** [Fuzss/leavemybarsalone#2]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

v3.1.0

### Notes (Required)

1. Open Minecraft with this mod and Appleskin
2. Get on a horse
3. Switch to a carrot item while also holding down right click, so as to eat it
4. The game crashes

### Crash Report (Required)

https://gist.github.com/Ezeyra/1018cc81290a85a6aefbf4cd6b36a33a

### latest.log (Optional)

https://gist.github.com/Ezeyra/b5b9f60a1944a5f0f5f1b7d3740a1ca9

**Comment by Fuzss** [comment]
Fixed in v3.1.1.
